.\" Manpage for bitcoind-cli.
.\" Contact bryan@nonni.io to correct errors or typos.
.TH man 8 "03 Dec 2022" "1.0" "bitcoind-cli man page"
.SH NAME
bitcoind-cli \- All the functionality of bitcoind plus some bonus controls
.SH SYNOPSIS
bitcoind-cli version
bitcoind-cli command [--version|-v] [options] ...
.SH DESCRIPTION
bitcoind-cli bridges bitcoind and the local OS to provide users with a more fine-grained control over bitcoind. It offers the ability
to interact with all three networks at the same time using flags. Basic functionality includes starting and stopping bitcoind on main, test and signet.
Extended functionality includes easily printing the PIDs of all bitcoind processes, detecting if bitcoind crashed, easily logging output on all networks,
and mounting / unmounting an external SSD.
.SH COMMANDS
help
        Print info about the cli, commands, usage and examples

setup [--interactive] ['\033[4mfilepath\033[0m']
        Set the path to your blockchain data in shell profile

        -i, --interactive
                Uses terminal prompts to setup cli and env

info [\033[4moptions\033[0m] ['\033[4network\033[0m']
        Print the PIDs for the currently running bitcoind processes

        -all, -testnet, -mainnet, -signet
                Single '-' style, explicit option flags for toggling network is mimicing
                the original bitcoind / bitcoin-cli interface

        -n, --network [all|mainnet|testnet|signet]
                Optional alternative to explicit, single '-' option flags

log [\033[4moptions\033[0m] ['\033[4network\033[0m']
        Continuously print the the bitcoind debug.log file(s) to stdout

        -all, -testnet, -mainnet, -signet
                Single '-' style, explicit option flags for toggling network is mimicing
                the original bitcoind / bitcoin-cli interface

        -n, --network [all|mainnet|testnet|signet]
                Optional alternative to explicit, single '-' option flags

disk '\033[4msubcommand\033[0m'
        Interact with external disk containing blockchain data

        mount
                Mount the external disk
        
        unmount
                Unmount the external disk

crash
        Detect improper shutdown of bitcoind leaving behind a .pid file

start [\033[4moptions\033[0m] ['\033[4network\033[0m']
        Start bitcoind, default settings: mainnet & logging disabled

        -all, -testnet, -mainnet, -signet
                Single '-' style, explicit option flags for toggling network is mimicing
                the original bitcoind / bitcoin-cli interface

        -n, --network [all|mainnet|testnet|signet]
                Optional alternative to explicit, single '-' option flags

        -l, --log
                Continuously print the the bitcoind debug.log file(s) to stdout

stop [\033[4moptions\033[0m] ['\033[4network\033[0m']
[\033[4moptions\033[0m] ['\033[4network\033[0m']
        Stop bitcoind, default settings: mainnet & logging disabled

        -all, -testnet, -mainnet, -signet
                Single '-' style, explicit option flags for toggling network is mimicing
                the original bitcoind / bitcoin-cli interface

        -n, --network [all|mainnet|testnet|signet]
                Optional alternative to explicit, single '-' option flags

        -l, --log
                Continuously print the the bitcoind debug.log file(s) to stdout

restart [\033[4moptions\033[0m] ['\033[4network\033[0m']
        Restart bitcoind, if no network passed, defaults to mainnet & logging disabled
        Restart is essentially a stop, sleep and start

        -all, -testnet, -mainnet, -signet
                Single '-' style, explicit option flags for toggling network is mimicing
                the original bitcoind / bitcoin-cli interface

        -n, --network [all|mainnet|testnet|signet]
                Optional alternative to explicit, single '-' option flags

        -l, --log
                Continuously print the the bitcoind debug.log file(s) to stdout

.SH EXAMPLES
-   Show the help menu
        % bitcoind-cli help

-   Set shell profile, blockchain data disk path, etc.
        % bitcoind-cli setup /Volumes/BLOCKCHAIN

-   Print the PIDs for all bitcoind network processes
        % bitcoind-cli info -all

-   Print the PID for bitcoind on mainnet
        % bitcoind-cli info -n mainnet

-   Mount the external drive contianing blockchain data
        % bitcoind-cli disk mount

-   Detect if bitcoind crashed previously and remove that .pid file
        % bitcoind-cli crash

-   Print the logs for all bitcoind network processes to stdout (WIP)
        % bitcoind-cli log -all

-   Print the log for bitcoind on mainnet to stdout
        % bitcoind-cli log -n mainnet

-   Start bitcoind on all networks
        % bitcoind-cli start -all

-   Start bitcoind on mainnet
        % bitcoind-cli start -n mainnet

-   Stop bitcoind on all networks
        % bitcoind-cli stop -all

-   Stop bitcoind on mainnet
        % bitcoind-cli stop -n mainnet

-   Restart (stop/start) bitcoind on all networks
        % bitcoind-cli restart -all

-   Restart bitcoind on mainnet
        % bitcoind-cli restart -n mainnet

.SH VERSION
Bitcoind-cli 0.0.1

.SH AUTHOR
Bryan Nonni (bryan@nonni.io): bitcoind-cli 0.0.1
Bitcoin Core Open Source (github.com/bitcoin/bitcoin): bitcoind 24.0.0
Satoshi Nakamoto (satoshin@gmx.com): bitcoind 0.0.1