#!/bin/bash
# ------------- VARS, ARGS & SETUP ------------- #
if [[ -e .profile && -z $BLOCKCHAIN_DIR ]]; then
  source .profile
fi

ARGS=($@)

SUBCOMMAND=${ARGS[0]}
if [[ ${ARGS[1]} == "-n" || ${ARGS[1]} == "--network" ]]; then
  NETWORK=${ARGS[2]}
  LOG=${ARGS[3]}
fi
NETWORK_ARG=${ARGS[1]}
NETWORK=$(echo "$NETWORK_ARG" | tr -d -)
LOG=${ARGS[2]}

if [[ ! -z $NETWORK_ARG && -z $NETWORK ]]; then
  echo "Error: Network flag -n | --network passed but no network arg detected!"
fi

BLOCKCHAIN=$BLOCKCHAIN_DIR
if [[ ! $SUBCOMMAND =~ ^(help|info|setup)$ && ! -d "$BLOCKCHAIN" ]]; then
  echo "BLOCKCHAIN_DIR=$BLOCKCHAIN not set or improperly set!"
  echo "Please use 'bitcoind-cli setup /path/to/blockchain/data' to set"
  exit 1;
else
  BITCOIN=$BLOCKCHAIN/.bitcoin
  CONF=$BITCOIN/bitcoin.conf
  
  LOG_FILE=$BITCOIN/debug.log
  PID_FILE=$BITCOIN/bitcoind.pid
  if [[ -e $PID_FILE ]]; then
    PID=$(cat $PID_FILE)
  fi
  
  TESTNET_LOG_FILE=$BITCOIN/testnet3/debug.log
  TESTNET=$BITCOIN/testnet3
  TESTNET_PID_FILE=$BITCOIN/testnet3/bitcoind.pid
  if [[ -e $TESTNET_PID_FILE ]]; then
    TESTNET_PID=$(cat $TESTNET_PID_FILE)
  fi
fi

# ------------- HELP ------------- #

print_help () {
  echo "NAME:" $'\n'$'\t'\
"Bitcoind CLI: control script for starting bitcoind" $'\n'$'\n'\
"COMMAND:" $'\n'$'\t'\
"bitcoind-cli: control script for starting bitcoind" $'\n'$'\n'\
"SUBCOMMANDS:" $'\n'$'\t'\
"help:    show help" $'\n'$'\t'\
"info:    show PIDs" $'\n'$'\t'\
"setup:   setup cli pathing" $'\n'$'\t'\
"log:     tail bitcoind logs" $'\n'$'\t'\
"start:   start bitcoind" $'\n'$'\t'\
"stop:    stop bitcoind" $'\n'$'\n'\
"USAGE:" $'\n'$'\t'\
"% bitcoind-cli subcommand [-arg | -option arg | --option arg]" $'\n'$'\t'\
"% bitcoind-cli help" $'\n'$'\t'\
"% bitcoind-cli info" $'\n'$'\t'\
"% bitcoind-cli setup /path/to/blockchain/data" $'\n'$'\t'\
"% bitcoind-cli log [-both | -mainnet | -testnet] [-n | --network <both | mainnet | testnet>]" $'\n'$'\t'\
"% bitcoind-cli start [-both | -mainnet | -testnet] [-n | --network <both | mainnet | testnet>] [-l | -log | --log]" $'\n'$'\t'\
"% bitcoind-cli stop [-both | -mainnet | -testnet] [-n | --network <both | mainnet | testnet>] [-l | -log | --log]" $'\n'$'\n'\
"EXAMPLES:" $'\n'$'\t'\
"- help: print info about the command, subcommands, usage and examples" $'\n'$'\t'\
"% bitcoind-cli help" $'\n'$'\n'$'\t'\
"- info: print the PIDs for the bitcoind processes" $'\n'$'\t'\
"% bitcoind-cli info" $'\n'$'\n'$'\t'\
"- setup: set the path to your blockchain data in shell profile" $'\n'$'\t'\
"% bitcoind-cli setup /Volumes/BLOCKCHAIN" $'\n'$'\n'$'\t'\
"- log: print the debug.log files for bitcoind using tail command" $'\n'$'\t'\
"% bitcoind-cli log" $'\n'$'\t'$'\t'\
"[-both | -testnet | -mainnet]" $'\n'$'\t'$'\t'\
"[-n | --network both | mainnet | testnet]" $'\n'$'\n'$'\t'\
"- start: start bitcoind, default: mainnet & logging disabled" $'\n'$'\t'\
"% bitcoind-cli start" $'\n'$'\t'$'\t'\
"[-both | -testnet | -mainnet]" $'\n'$'\t'$'\t'\
"[-n | --network both | mainnet | testnet]" $'\n'$'\t'$'\t'\
"[-l | -log | --log]" $'\n'$'\n'$'\t'\
"- stop: start bitcoind, default: mainnet & logging disabled" $'\n'$'\t'\
"% bitcoind-cli stop" $'\n'$'\t'$'\t'\
"[-both | -testnet | -mainnet]" $'\n'$'\t'$'\t'\
"[-n | --network both | mainnet | testnet]" $'\n'\
"VERSION:"$'\n'$'\t'\
"0.0.1"$'\n';
  exit 0;
}

# ------------- SETUP ------------- #

setup () {
  if [[ -e .profile ]]; then
    echo "Setup already complete!"
  else
    echo $'\n'"export BLOCKCHAIN_DIR=${ARGS[1]}" >> .profile
    source .profile
    echo "BLOCKCHAIN_DIR=$BLOCKCHAIN_DIR"
    echo "bitcoind-cli setup success!"
  fi
  exit 0;
}

# ------------- INFO ------------- #

info () {
  case $NETWORK in
    both|"")  if [[ -e "$PID_FILE" && -e "$TESTNET_PID_FILE" ]]; then
                echo "bitcoind PID: $PID";
                echo "bitcoind testnet PID: $TESTNET_PID";
              fi;;
    mainnet)  if [[ -e "$PID_FILE" ]]; then
                echo "bitcoind PID: $PID";
              fi;;
    testnet)  if [[ -e "$TESTNET_PID_FILE" ]]; then
                echo "bitcoind testnet PID: $TESTNET_PID";
              fi;;
    *) echo "PID file not detected. Are you sure bitcoind on $NETWORK?"
  esac;
}

# ------------- LOG ------------- #

log () {
  echo "Logging enabled!"
  case $NETWORK in
    both|"") log_both;;
    mainnet) log_mainnet;;
    testnet) log_testnet;;
    *) echo "Network arg missing or improperly passed!"
        exit 1;;
  esac;
}

log_both () {
  echo "Logging mainnet $LOG_FILE"
  tail -f $LOG_FILE
  echo "Logging testnet $TESTNET_LOG_FILE"
  tmux new-session -d -s testnet_logs "tail -f /Volumes/BLOCKCHAIN/.bitcoin/testnet3/debug.log"
  tmux attach;
}

log_mainnet () {
  echo "Logging mainnet $LOG_FILE"
  tail -f $LOG_FILE;
}

log_testnet () {
  echo "Logging testnet $TESTNET_LOG_FILE"
  tail -f $TESTNET_LOG_FILE;
}

# ------------- START / STOP ------------- #

start_stop_restart () {
  case $SUBCOMMAND in
      start) case $NETWORK in
              both) start_both;;
              mainnet|"") start_bitcoind;;
              testnet) start_bitcoind_testnet;;
              *) echo "Network arg missing or improperly passed!"; exit 1;;
            esac;;
      stop) case $NETWORK in
              both) stop_both;;
              mainnet|"") stop_bitcoind;;
              testnet) stop_bitcoind_testnet;;
              *) echo "Network arg missing or improperly passed!"; exit 1;;
            esac;;
   restart) case $NETWORK in
              both) restart_both;;
              mainnet|"") restart_bitcoind;;
              testnet) restart_bitcoind_testnet;;
              *) echo "Network arg missing or improperly passed!"; exit 1;;
            esac;;
      *) echo "Subcommand missing or improperly passed!"; exit 1;;
    esac;
}

# ---- START ---- #

start_both () {
  start_bitcoind;
  start_bitcoind_testnet;
  if [[ ! -z "$LOG" && "$LOG" =~ ^(-l|-log|--log)$ ]]; then
    log;
  else
    echo "Logging disabled!"
  fi;
}

start_bitcoind () {
  if [ ! -e "$PID_FILE" ]; then
    /usr/local/bin/bitcoind -conf=$CONF
    echo "Running bitcoind from $BITCOIN_DIR"
  else
    echo "Already running bitcoin on mainnet from $BITCOIN_DIR"
  fi
  echo "bitcoind PID: $PID";
  
  if [[ ! -z "$LOG" && "$LOG" =~ ^(-l|-log|--log)$ ]]; then
    log;
  else
    echo "Logging disabled!"
  fi;
}

start_bitcoind_testnet () {
  if [ ! -e "$TESTNET_PID_FILE" ]; then
    /usr/local/bin/bitcoind -testnet -conf=$CONF
    echo "Running bitcoind testnet from $BITCOIN_DIR"
  else
    echo "Already running bitcoind testnet from $BITCOIN_DIR"
  fi
  echo "bitcoind testnet PID: $TESTNET_PID";

  if [[ ! -z "$LOG" && "$LOG" =~ ^(-l|-log|--log)$ ]]; then
    log;
  else
    echo "Logging disabled!"
  fi;
}

# ---- STOP ---- #

stop_both () {
  stop_bitcoind;
  stop_bitcoind_testnet;
  if [[ ! -z "$LOG" && "$LOG" =~ ^(-l|-log|--log)$ ]]; then
    log;
  fi;
}

stop_bitcoind () {
  if [ -e "$PID_FILE" ]; then
    /usr/local/bin/bitcoin-cli -conf=$CONF stop
    # do check for bitcoind still starting
    # if kill -9, must remove .pid files
    echo "Stopping bitcoind from $BITCOIN_DIR"
    PID=$(cat $PID_FILE)
    echo "bitcoind PID $PID stopped!";
  else
    echo "$PID_FILE file not detected! Are you sure bitcoind is running on mainnet?"
  fi;
}

stop_bitcoind_testnet () {
 if [ -e "$TESTNET_PID_FILE" ]; then
    /usr/local/bin/bitcoin-cli -testnet -conf=$CONF stop
    # do check for bitcoind still starting
    # if kill -9, must remove .pid files
    echo "Stopping bitcoind testnet from $BITCOIN_DIR"
    TESTNET_PID=$(cat $TESTNET_PID_FILE)
    echo "bitcoind PID $TESTNET_PID stopped!";
  else
    echo "$TESTNET_PID_FILE file not detected! Are you sure bitcoind is running on testnet?"
  fi;
}

# ------------- RESTART ---------- #
restart_both () {
  stop_both;
  sleep 30;
  start_both;
}

restart_bitcoind () {
  stop_bitcoind;
  sleep 10;
  start_bitcoind;
}

restart_bitcoind_testnet () {
  stop_bitcoind_testnet;
  sleep 10;
  start_bitcoind_testnet;
}

# ------------- SUBCOMMAND CHECK ------------- #

case $SUBCOMMAND in
  help) print_help;;
  info) info;;
  setup) setup;;
  log) log;;
  start|stop|restart) start_stop_restart;;
  *) echo "No subcommand passed!"; exit 1;;
esac